INSERT INTO user (`id`, `name`,`age`)VALUES(1,'Vlad',26);
INSERT INTO user (`id`, `name`,`age`)VALUES(2,'Yulia',27);
INSERT INTO user (`id`, `name`,`age`)VALUES(3,'Oksana',23);
INSERT INTO user (`id`, `name`,`age`)VALUES(4,'Vasyl',23);
INSERT INTO user (`id`, `name`,`age`)VALUES(5,'Yurii',22);
INSERT INTO user (`id`, `name`,`age`)VALUES(6,'Roman',24);
INSERT INTO user (`id`, `name`,`age`)VALUES(7,'Valerii',25);
INSERT INTO user (`id`, `name`,`age`)VALUES(8,'Dima',19);
INSERT INTO user (`id`, `name`,`age`)VALUES(9,'Ruslan',24);
INSERT INTO user (`id`, `name`,`age`)VALUES(10,'Bogdan',21);


INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(1,'RED','Article about nature',1);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(2,'BLUE','Article about cars',2);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(3,'GREEN','Article about machine learning',3);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(4,'PINK','Article about IT industry',4);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(5,'PURPLE','Article about bicycle',5);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(6,'BROWN','Article about weather',6);
INSERT INTO article(`id`,`color`,`text`,`user_id`)VALUES(7,'WHITE','Article about sun',6);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(8,'YELLOW','Article about popular people',6);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(9,'RED','Article about fish',7);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(10,'YELLOW','Article about social life',8);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(11,'BLACK','Article about kids',7);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(14,'GREY','Article about police',7);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(15,'BLUE','Article about goverment',9);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(16,'PINK','rticle about psychology',8);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(17,'WHITE','Article about mathematics',2);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(18,'YELLOW','Article about physics',1);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(19,'RED','Article about chemistry',1);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(20,'GREEN','Article about polution',3);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(21,'RED','Article about logistics',4);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(22,'RED','Article about death',4);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(23,'BROWN','Article about smartphones',2);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(24,'RED','Article about laptops',3);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(25,'RED','Article about life',5);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(26,'WHITE','Article about green peace',2);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(27,'RED','Article about politics',5);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(28,'BLACK','Article about products',2);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(29,'GREY','Article about human body',8);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(30,'RED','Article about tv show',9);
INSERT INTO article(`id`, `color`,`text`,`user_id`)VALUES(31,'RED','Article about adventures',7);
